# #976d1b
add_newline = true
format = """$directory$character$status$git_branch$git_status
[ó°£](fg:#976d1b) """

[character]
success_symbol = "[ó°£](fg:#976d1b)"
error_symbol = "[ó°£](fg:#976d1b)"
vicmd_symbol = "[ó°£](fg:#976d1b)"


[git_branch]
format = '[$branch]($style) '
style = 'fg:#976d1b'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
format = '\($virtualenv\) '

[git_status]
format = '$all_status$ahead_behind '
ahead = '[ğŸ˜¼](fg:#976d1b) '
behind = '[ğŸ˜¼](fg:#976d1b) '
staged = '[ğŸ˜½](fg:#adc982) '
deleted = '[ğŸ˜¿](fg:#c22627) '
renamed = '[ğŸ˜¾](fg:#976d1b) '
stashed = '[ğŸ˜»](fg:#976d1b) '
untracked = '[ğŸ˜¹](white) '
modified = '[ğŸ˜¾](fg:#976d1b) '
conflicted = '[ğŸ™€](fg:#976d1b) '
diverged = 'diverged'
up_to_date = '[ğŸ±](fg:#e09e1a)'

[directory]
style = "white"
truncation_length = 1
truncation_symbol = ""
# fish_style_pwd_dir_length = 1

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
symbol = 'âœ˜ '
