# #bf6d36
add_newline = true
format = """$directory$character$status$git_branch$git_status$cmd_duration${custom.timer}
[ó°£](fg:#bf6d36) """

[character]
success_symbol = "[ó°£](fg:#bf6d36)"
error_symbol = "[ó°£](fg:#bf6d36)"
vicmd_symbol = "[ó°£](fg:#bf6d36)"


[git_branch]
format = '[$branch]($style) '
style = 'fg:#bf6d36'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
format = '\($virtualenv\) '

[git_status]
format = '$all_status$ahead_behind '
ahead = '[ğŸ˜¼](fg:#bf6d36) '
behind = '[ğŸ˜¼](fg:#bf6d36) '
staged = '[ğŸ˜½](fg:#adc982) '
deleted = '[ğŸ˜¿](fg:#c22627) '
renamed = '[ğŸ˜¾](fg:#bf6d36) '
stashed = '[ğŸ˜»](fg:#bf6d36) '
untracked = '[ğŸ˜¹](white) '
modified = '[ğŸ˜¾](fg:#bf6d36) '
conflicted = '[ğŸ™€](fg:#bf6d36) '
diverged = 'diverged'
up_to_date = '[ğŸ±](fg:#e09e1a)'

[directory]
style = "white"
truncation_length = 1
truncation_symbol = ""
# fish_style_pwd_dir_length = 1

[cmd_duration]
style = "fg:#bf6d36"
format = '[$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = 'âœ˜ '
